name: Release
on:
  release:
    type: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install zest.releaser
      - name: Release
        run: |
          cat <<< '${{ secrets.pypirc }}' > $HOME/.pypirc
          fullrelease --no-input
