name: Release
on:
  push:
    tags:
      - '\d+\.\d+\.\d+'
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt
          pip install -e .
      - name: Static analysis
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics
          isort -c .
          mypy ./hmm_profile/
      - name: Test with pytest
        env:
          HMM_PROFILE_RUN_INTEGRITY_TESTS: 'TRUE'
        run: |
          python setup.py test --addopts -s
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade zest.releaser wheel
      - name: Configure git
        run: |
          git config --global user.email "zest.releaser@example.com"
          git config --global user.name "Zest Releaser"
      - name: Configure pypi
        run: |
          cat <<< '${{ secrets.pypirc }}' > $HOME/.pypirc
      - name: Release
        run: |
          fullrelease --no-input
