name: Release

on:
  release:
    type: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install zest.releaser[recommended]
      - name: Release
        run: |
          cat <<< '${{ secrets.pypirc }}' > $HOME/.pypirc
          release --no-input
          postrelease --no-input
